# Generated by Django 3.0 on 2020-09-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'COFFEE MACHINE LARGE'), ('COFFEE_MACHINE_SMALL', 'COFFEE MACHINE SMALL'), ('ESPRESSO_MACHINE', 'ESPRESSO MACHINE')], default='COFFEE_MACHINE_LARGE', max_length=250)),
                ('water_line_compatible', models.BooleanField(default=False)),
            ],
        ),
    ]
