# Generated by Django 3.0 on 2020-09-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('DOZEN', '1 dozen (12)'), ('3_DOZEN', '3 dozen (36)'), ('5_DOZEN', '5 dozen (60)'), ('7_DOZEN', '7 dozen (84)')], default='COFFEE_POD_LARGE', max_length=250)),
                ('coffee_flavor', models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'COFFEE FLAVOR VANILLA'), ('COFFEE_FLAVOR_CARAMEL', 'COFFEE FLAVOR CARAMEL'), ('COFFEE_FLAVOR_PSL', 'COFFEE FLAVOR PSL'), ('COFFEE_FLAVOR_MOCHA', 'COFFEE FLAVOR MOCHA'), ('COFFEE_FLAVOR_HAZELNUT', 'COFFEE FLAVOR HAZELNUT')], default='COFFEE_FLAVOR_VANILLA', max_length=250)),
                ('pack_size', models.CharField(choices=[('DOZEN', '1 dozen (12)'), ('3_DOZEN', '3 dozen (36)'), ('5_DOZEN', '5 dozen (60)'), ('7_DOZEN', '7 dozen (84)')], default='DOZEN', max_length=250)),
            ],
        ),
    ]
