# Generated by Django 3.0 on 2020-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_coffeepod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepod',
            name='product_type',
            field=models.CharField(choices=[('COFFEE_POD_LARGE', 'COFFEE POD LARGE'), ('COFFEE_POD_SMALL', 'COFFEE POD SMALL'), ('ESPRESSO_POD', 'ESPRESSO POD')], default='COFFEE_POD_LARGE', max_length=250),
        ),
    ]
