# Generated by Django 3.0 on 2020-09-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20200912_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeemachine',
            name='model_type',
            field=models.CharField(choices=[('BASE_MODEL', 'BASE MODEL'), ('PREMIUM_MODEL', 'PREMIUM MODEL'), ('DELUXE_MODEL', 'DELUXE MODEL')], default='BASE_MODEL', max_length=250),
        ),
        migrations.AlterField(
            model_name='coffeemachine',
            name='product_type',
            field=models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'COFFEE MACHINE LARGE'), ('COFFEE_MACHINE_SMALL', 'COFFEE MACHINE SMALL'), ('ESPRESSO_MACHINE', 'ESPRESSO MACHINE')], default='COFFEE_MACHINE_SMALL', max_length=250),
        ),
    ]
